default: &default
  adapter: postgresql
  encoding: SQL_ASCII

development:
  <<: *default
  database: hacker_news_clone_development

test:
  <<: *default
  database: hacker_news_clone_test

production:
  <<: *default
  database: hacker_news_clone_production
  username: hacker_news_clone
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
